export { default as DescriptionBlock } from './DescriptionBlock'
export { default as ProductInfoBlock } from './ProductInfoBlock'
export { default as ImageBlock } from './ImageBlock'
export { default as TitleBlock } from './TitleBlock'
export { default as StockBlock } from './StockBlock'
export { default as PriceBlock } from './PriceBlock'